<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'app\\contentresult' => '/app/ContentResult.php',
                'app\\contentresulthandler' => '/app/ContentResultHandler.php',
                'app\\contentresultroute' => '/app/ContentResultRoute.php',
                'app\\factory' => '/app/Factory.php',
                'app\\sampleexecutable' => '/app/SampleExecutable.php',
                'app\\sampleroute' => '/app/SampleRoute.php',
                'app\\samplewebsite' => '/app/SampleWebsite.php',
                'framework\\application' => '/framework/Application.php',
                'framework\\contentresponse' => '/framework/ContentResponse.php',
                'framework\\executable' => '/framework/Executable.php',
                'framework\\getrequest' => '/framework/request/GetRequest.php',
                'framework\\getroutetemplate' => '/framework/routing/GetRouteTemplate.php',
                'framework\\request' => '/framework/request/Request.php',
                'framework\\requestrouter' => '/framework/routing/RequestRouter.php',
                'framework\\response' => '/framework/Response.php',
                'framework\\result' => '/framework/Result.php',
                'framework\\resulthandler' => '/framework/routing/ResultHandler.php',
                'framework\\resultroute' => '/framework/routing/ResultRoute.php',
                'framework\\resultrouter' => '/framework/routing/ResultRouter.php',
                'framework\\resultroutetemplate' => '/framework/routing/ResultRouteTemplate.php',
                'framework\\route' => '/framework/routing/Route.php',
                'framework\\runner' => '/framework/Runner.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
